### ISSUE TITLE
Redaction field values should be lowercase 

### ISSUE THREAD

**Issue by sjparkinson** [signalsciences/terraform-provider-sigsci#120]
For `sigsci_site_redaction`, if the value of `field` contains non-lowercase characters Terraform will always try to apply changes based on the response from the API which is lowercasing the submitted value.

```
# module.internal_products_site.sigsci_site_redaction.request_params["apiKey"] will be updated in-place
  ~ resource "sigsci_site_redaction" "request_params" {
      ~ field           = "apikey" -> "apiKey"
        id              = "..."
        # (2 unchanged attributes hidden)
    }
```

**Comment by shawnps** [comment]
@sjparkinson I could do something like this, where TF won't try to apply changes if the `field` returned by the API matches the lowercase version of the `field` from the `sigsci_site_redaction`:

```
+       field := d.Get("field").(string)
+       if strings.ToLower(field) == redaction.Field {
+               err = d.Set("field", field)
+       } else {
+               err = d.Set("field", redaction.Field)
+       }
```

The other option is to return an error when creating a redaction with uppercase letters, asking the user to lowercase the `field` in the `.tf`:

I think the second option is probably better, because the first option may lead users to believe the redaction field is case-sensitive.

**Comment by shawnps** [comment]
@sjparkinson sorry, actually I didn't know about [`DiffSuppressFunc`](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#diffsuppressfunc) which seems to be the correct way to fix this. I'll have a PR up shortly.
