### ISSUE TITLE
Cannot add a second action if "Type" is there (example signal), need another Action group

### ISSUE THREAD

**Issue by farzam-sigsci** [signalsciences/terraform-provider-sigsci#42]
Our example config, below I list how I was able to get it to work by separating out "type" & "signal" to their own action conditions.

resource "sigsci_site_rule" "test" {
site_short_name = sigsci_site.my-site.short_name
type = "signal"
group_operator = "any"
enabled = true
reason = "Example site rule update"
signal = "SQLI"
expiration = ""

conditions {
type = "single"
field = "ip"
operator = "equals"
value = "1.2.3.4"
}

conditions {
type = "single"
field = "ip"
operator = "equals"
value = "1.2.3.5"
conditions {
type = "multival"
field = "ip"
operator = "equals"
group_operator = "all"
value = "1.2.3.8"
}
}

actions {
type = "excludeSignal"
signal = "corp.signal_id" ### From our GH
}
}

#####
actions {
type = "excludeSignal"
signal = "corp.signal_id" ### DOES NOT WORK RIGHT
}
}

TO MAKE IT WORK
actions {
type = "excludeSignal" ### Need to
}
}

actions {
signal = "corp.signal_id" ### Need to
}
}

- [ ] 

- [ ] 

-

**Comment by jbhanrahan** [comment]
Sorry to reply so late, but both type and signal in the same actions block is definitely allowed, there is an example in main.tf and I can run this file without issues. And actually I can run your first example too, but your proposed solution would be illegal as type is a required field so I might be misunderstanding you.

As to what the actual problem is, I don't believe any other action than exclude signal is allowed for this type of rule and the signal is already defined at the rule level so there isn't a need to include it in actions.  It looks like additional actions fields are ignored by the api as well so I think thats whats happening with your second actions block.  

If you are having trouble structuring your rule correctly, you can create the rule in the console ui and inspect the json payload sent.  In most cases you are just replicating this data structure in terraform and this will give you a huge hint as to where your error might be and what the fields should be set to
